spring:
  application:
    name: backend-service
server:
  port: ${PORT:8081}
eureka:
  client:
    serviceUrl:
      # url of service registry : default value
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
