version: "3.7"
services:
  backend-service:
    build:
      #location of dockerfile
      dockerfile: Dockerfile
      context: ./backend-service
      #name
    image: backend-service:latest
    restart: on-failure
    depends_on:
      - db #not yet defined
    environment:
      # can use name of service to automatically map
      - JDBC_URL = "jdbc:postgresql://db:5432/project_db?user=project_user&password=project_pw"
    ports:
      - 8081:8081
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB = project_db
      - POSTGRES_USER = project_user
      - POSTGRES_PASSWORD = project_pw
  frontend-service:
    build:
      #location of dockerfile
      dockerfile: Dockerfile
      context: ./frontend-service-service
      #name
    image: frontend-service:latest
    restart: on-failure
    depends_on:
      - db #not yet defined
    environment:
      # can use name of service to automatically map
      - BACKEND_URL = "http://backend-service:8081"
    ports:
      - 8082:8082

